[package]
authors = ["J. David Smith <emallson@atlanis.net>"]
edition = "2018"
name = "sharktocrab-bot"
version = "0.1.0"
[dependencies]
env_logger = "*"
log = "*"
rand = "*"

[dependencies.serenity]
features = ["framework", "standard_framework"]
version = "*"
